- name: Install postgresql and dependencies
  apt:
    update_cache: yes
    pkg:
    - postgresql 
    - libpq-dev
    - postgresql-contrib
    - python3-dev
    - python3-pip

- name: Install psycopg2
  pip:
    name: psycopg2