- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: restart gunicorn
  ansible.builtin.systemd:
    name: "gunicorn-{{ project_name }}.service"
    state: restarted