- name: Installing certbot
  ansible.builtin.apt:
    pkg:
    - certbot 
    - python3-certbot-nginx

# - name: Challenge certificate
#   ansible.builtin.shell: certbot certonly -n --nginx -d {{ nginx_server_name }}

- name: Replacing nginx configuration
  ansible.builtin.template:
    src: "../templates/nginx-ssl-template.j2"
    dest: /etc/nginx/sites-available/{{ project_name }}
  notify:
    - restart nginx