- name: Migrate database
  shell: "{{ project_base_dir }}/venv/bin/python3 manage.py migrate"
  args:
    chdir: "{{ project_codebase_dir }}"

- name: Collecting static files
  shell: "{{ project_base_dir }}/venv/bin/python3 manage.py collectstatic --noinput"
  args:
    chdir: "{{ project_codebase_dir }}"