- name: Install python3 packages
  apt:
    pkg:
    - python3
    - python3-dev
    - python3-venv

- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3

- name: Install requirements
  pip: 
    requirements: "{{ project_codebase_dir }}/requirements.txt"
    virtualenv: "{{ project_base_dir }}/venv"
    virtualenv_python: python3

- name: Install gunicorn
  pip: 
    name: gunicorn
    virtualenv: "{{ project_base_dir }}/venv"
    virtualenv_python: python3