- name: Clone project codebase
  import_tasks: create-codebase.yaml

- name: Install python requirements
  import_tasks: install-requirements.yaml

- name: run django managements
  import_tasks: django-management.yaml